### ISSUE TITLE
dependabot で eslint 系を groups でまとめる

### ISSUE THREAD

**Issue by mitsuharu** [yumemi-inc/daigirin-template#149]
https://docs.github.com/ja/code-security/dependabot/working-with-dependabot/dependabot-options-reference#groups--

こんな感じで、まとまる

```yml
  - package-ecosystem: "npm"
    directory: "/"
    open-pull-requests-limit: 10
    schedule:
      interval: "weekly"
    groups:
      update-eslint:
        patterns:
          - "eslint"
          - "eslint-*"
          - "@eslint/*"
      update-textlint:
        patterns:
          - "textlint"
          - "textlint-*"
```
