### ISSUE TITLE
プロジェクトにフォントを埋め込む

### ISSUE THREAD

**Issue by mitsuharu** [yumemi-inc/daigirin-template#55]
いまローカルとdockerをサポートしているが、環境が異なればフォントが異なる。
ViviliostyleはWebfontをサポートしているので、cssでフォント（たとえばGoogle Font）を指定して、
どの環境でもフォントが変わらないようにする。

```css
@import url('https://fonts.googleapis.com/css2?family=Noto+Sans+JP&display=swap');
:root {
  font-family: "Noto Serif JP",  "Neue Frutiger World", "Verdana", "Yakumono", "body", "Hiragino Sans", sans-serif;
  font-weight: 400;
  line-height: 1.7;
}
```
