### ISSUE TITLE
目次の自動生成に対応する

### ISSUE THREAD

**Issue by mitsuharu** [yumemi-inc/daigirin-template#99]
この issue が解決するには
- [ ] テンプレを修正して、タイトル部から h1 タグを取り除く
- [ ] viviliostyle が目次自動生成に ignore オプションを追加する

vivliostyle.config.js にて、次のように設定すると、見出しの階層を考慮した目次が自動生成される。

```js
  toc: {
    title: '目次',
    sectionDepth: 2,
  },
```

![スクリーンショット 2024-11-21 16 41 11](https://github.com/user-attachments/assets/62592050-8f9d-4309-9bf2-989972a53913)

しかしながら、

- いまのテンプレのタイトル部の h1 と干渉する
  - h1 を使わずに作ればよさそう？ 

```
<div class="doc-header">
  <h1>サンプルチャプターのタイトル</h1>
  <div class="doc-author">サンプルチャプターの著者</div>
</div>
```

- 奥付けで使っている h2 が反応する
  - h2 を外しても、反応するので、おそらくファイル単位で作ってる？
  - ignoreオプションを~探す~ 
      - なかった
      - 本家で issue を立ててもらった
          - https://github.com/vivliostyle/vivliostyle-cli/issues/544

https://github.com/vivliostyle/vivliostyle-cli/blob/main/examples/table-of-contents/README.md
https://docs.vivliostyle.org/#/vivliostyle-cli#creating-a-table-of-contents

**Comment by macneko-ayu** [comment]
## いまのテンプレのタイトル部の h1 と干渉する問題

以下のように CSS と Markdown 内の HTML タグを修正することでタイトル部は修正可能っぽい。
なお、CSS は vivliostyle-theme-macneko-techbook で修正を行わないといけない。

### markdown

```markdown
<div class="doc-header">
  <div class="doc-title">サンプルチャプターのタイトル</div>
  <div class="doc-author">サンプルチャプターの著者</div>
</div>
```

### CSS

```css
div.doc-title {
  /* h1 の指定を @vivliostyle/theme-base/css/common/basic.css からコピーしたもの */
  break-after: var(--vs--h1-break-after, var(--vs--heading-break-after));
  break-inside: var(--vs--h1-break-inside, var(--vs--heading-break-inside));
  font-family: var(--vs--h1-font-family, var(--vs--heading-font-family));
  font-feature-settings: var(--vs--h1-font-feature-settings,
      var(--vs--heading-font-feature-settings));
  font-kerning: var(--vs--h1-font-kerning, var(--vs--heading-font-kerning));
  font-size: var(--vs--h1-font-size);
  font-stretch: var(--vs--h1-font-stretch, var(--vs--heading-font-stretch));
  font-variant: var(--vs--h1-font-variant, var(--vs--heading-font-variant));
  font-variation-settings: var(--vs--h1-font-variation-settings,
      var(--vs--heading-font-variation-settings));
  font-weight: var(--vs--h1-font-weight, var(--vs--heading-font-weight));
  hyphens: var(--vs--h1-hyphens, var(--vs--heading-hyphens));
  letter-spacing: var(--vs--h1-letter-spacing,
      var(--vs--heading-letter-spacing));
  line-height: var(--vs--h1-line-height, var(--vs--heading-line-height));
  margin-block: var(--vs--h1-margin-block, var(--vs--heading-margin-block));
  margin-inline: var(--vs--h1-margin-inline, var(--vs--heading-margin-inline));
  text-align: var(--vs--h1-text-align, var(--vs--heading-text-align));
  text-indent: var(--vs--h1-text-indent, var(--vs--heading-text-indent));
  text-spacing: var(--vs--h1-text-spacing, var(--vs--heading-text-spacing));
  word-break: var(--vs--h1-word-break, var(--vs--heading-word-break));
  word-spacing: var(--vs--h1-word-spacing, var(--vs--heading-word-spacing));
}
```
